Dynamicroles
lesterchan/wp-downloadmanager pull request #23
Opened 2017-06-19 15:38 UTC by suhailasif

Custom roles can now be selected for file permissions. Previously it was hard coded and only General Roles were available for file permissions.

From now on any custom role added, shows up for file permissions drop box. 

It is a multiple select box now, you can choose all the users you want to grant permissions to download file. Administrator have permission to download all the files by default.

2017-06-20 04:46 UTC, lesterchan requested changes
Generally, it is ok, the code quality is inconsistent. Sometimes there is space before/after `(`, sometimes there is not. Let's follow WP and use space before and after `(`

2017-06-20 04:46 UTC, lesterchan commented on wp-downloadmanager.php
> +function generate_user_roles_select( $permission = array(), $mode = 'create' ) {
I think should prefix it with downloads_ generate_user_roles_select

2017-06-20 04:46 UTC, lesterchan commented on wp-downloadmanager.php
> +	if ($mode == 'edit' ) {
`if ( $mode === 'edit' ) {`

2017-06-20 04:46 UTC, lesterchan commented on wp-downloadmanager.php
> +	if ( ! empty( $_POST['file_permission'] ) ) {
Need to sanitize `$_POST['file_permission']`

2017-06-22 12:04 UTC, suhailasif commented
I have done all the required fixes, some issue i faced while working on it. Fixed theme too.

2017-06-22 12:06 UTC, lesterchan commented
Thanks, I will review them when I get back from my holiday in Jul.

2017-06-22 12:07 UTC, suhailasif commented
Great! No worries.

2017-07-04 06:22 UTC, lesterchan commented on wp-downloadmanager.php
> +	$permissoins_post = $_POST['file_permission'];
$permissions

2017-07-04 06:22 UTC, lesterchan commented on wp-downloadmanager.php
> +		$permission = explode( '+', $permission );
Actually, any reason we use + instead of ","? I would prefer it to be "," rather than "+" as it is more readable and doesn't need to be urlencoded

2017-07-04 06:22 UTC, lesterchan commented on wp-downloadmanager.php
> +							"file_permission varchar(255) NOT NULL default '0',".
If we change the col, we need to provide exisiting user an upgrade path.

Similar to https://github.com/lesterchan/wp-polls/blob/master/wp-polls.php#L1881-L1888

2017-07-04 06:22 UTC, lesterchan commented on wp-downloadmanager.php
> +			return $allowed;
`return true;`

`$allowed = true;` is no longer needed.

2017-07-04 06:22 UTC, lesterchan commented on wp-downloadmanager.php
> +	return $allowed;
`return false;`

2017-07-04 06:22 UTC, lesterchan commented on wp-downloadmanager.php
> +	$allowed = false;
Don't need this line.

2017-07-04 06:22 UTC, lesterchan commented on wp-downloadmanager.php
> +		$permissions[] = filter_var( $permission, FILTER_SANITIZE_STRING );
maybe we should do a `$permissions[] = sanitize_text_field( $permission );`

2017-07-04 06:22 UTC, lesterchan commented on wp-downloadmanager.php
> +		$permissions = $_POST['file_permission'];
After sanitizing it, why do we use the unsanitized version again?

2017-07-04 06:22 UTC, lesterchan commented on download-add.php
> +            $file_permission = "'" . get_file_permissions_info(). "'";
Why we need this? Instead can `get_file_permissions_info()` return a string instead of int?

2026-08-09 02:50 UTC, lesterchan commented
Thanks for this, and sorry it has sat here so long.

The plugin is being rewritten for a major version — the files this patch touches have moved or gone, so there is no longer a branch this can merge into. Closing it rather than leaving it open indefinitely. If the feature still matters to you once the new version is out, a fresh PR against it would be very welcome.

2026-08-09 02:50 UTC, closed without merging